### ISSUE TITLE
Increased movement speed while feared

### ISSUE THREAD

**Issue by Jezzawar** [elysium-project/tbc-bug-tracker#702] opened 2019-06-29 12:25 UTC
**Summary:** 
After being fear in the area by a fear totem the running speed was extremly fast and made me outrun the mob. 
**Steps to Reproduce:** 
Awaiting for terror totem to respawn
**Expected Results:** 
![image](https://user-images.githubusercontent.com/52182503/60384069-618b1e80-9a71-11e9-8744-596c8d8061bc.png)

**Actual Result:**
increased movement speed
**Additional Information:**
![image](https://user-images.githubusercontent.com/52182503/60384032-1b35bf80-9a71-11e9-8ff0-fbc2fecf1522.png)

**Comment by McMittens** [comment] 2019-07-18 11:19
Duplicate of https://github.com/elysium-project/tbc-bug-tracker/issues/288

**Closed by McMittens** 2019-07-18 11:19 UTC
