### ISSUE TITLE
Theramore Ship in Menethil Bay

### ISSUE THREAD

**Issue by Booksie** [elysium-project/tbc-bug-tracker#714] opened 2019-07-08 12:07 UTC
**Summary:** 
Standing on the dock at Menethil the ship to Theramore appears in the horizon but comes nowhere near Menethil, hangs around far away in the distance then leaves for Theramore without allowing a boarding by players waiting patiently at the dock. The ship to Darnassus works fine.

**Steps to Reproduce:** 
Stand at the Theramore dock at Menethil and look into the horizon over the ocean.

**Expected Results:**
Script the waypoints of the Theramore ship to dock properly at Menethil, allow boarding by players and disembark to Theramore in a reasonable time limit.

**Additional Information:**
It's the long way to Theramore from Darkshore if this isn't fixed at TBC launch.

**Comment by McMittens** [comment] 2019-07-18 11:05
Duplicate of https://github.com/elysium-project/tbc-bug-tracker/issues/480
Please comment there if anything new pops up!

**Closed by McMittens** 2019-07-18 11:05 UTC
