### ISSUE TITLE
Felsworn gas mask isnt working.

### ISSUE THREAD

**Issue by corytrevormakker** [elysium-project/tbc-bug-tracker#828] opened 2019-08-15 18:57 UTC
**Summary:** 
The Legion communicator you are supposed to interact with isnt there.

**Steps to Reproduce:** 
Go there and look
**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by invwax** [comment] 2019-09-19 08:21
dupe of #817

**Closed** 2019-12-13 01:17 UTC
Labels: Fixed
