### ISSUE TITLE
boat on Azuremyst 

### ISSUE THREAD

**Issue by Pikabluee** [elysium-project/tbc-bug-tracker#721] opened 2019-07-16 00:24 UTC
**Summary:**  glitched / bugged boat Azuremyst to darkshore

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by Pikabluee** [comment] 2019-07-16 00:26
The Boat that goes from Azuremyst draenei starting zone to Darkshore is gliched out or bugged out it appears and then suddenly departs seconds later up so it is impossible to go beyond lv 25

**Comment by McMittens** [comment] 2019-07-18 11:05
Duplicate of https://github.com/elysium-project/tbc-bug-tracker/issues/480
Please psot there if anything new pops up!

**Closed by McMittens** 2019-07-18 11:05 UTC
