### ISSUE TITLE
Regeneration with spirit

### ISSUE THREAD

**Issue by Trigerxx** [elysium-project/tbc-bug-tracker#797] opened 2019-08-13 09:59 UTC
When opening character info can see in the column "Spell" and seeing "Mana regen:" any number, but my count 66 MP/5. 
When leaving combat i observed that real regeneration mana much smaller. The real count near 15-29 MP/5. And i have similar situation with health. I don't know which number should be for health, but if compare Vanilla it's smaller in 2-4 times.

**Comment by Ziggy-QA** [comment] 2019-08-13 10:59
I don't really understand what the issue is here, but generally you want to give more information. You say this is how your currently regaining mana but not giving me the expected/correct numbers. Since every stat has been rebalanced in 2.4 TBC its not viable to compare to vanilla.

![image](https://user-images.githubusercontent.com/45450044/62936289-685ac000-bd97-11e9-8dac-45f9b63d729e.png)

In patch 2.4 spirit was changed to be like that. Also keep in mind, that while the character screen tells you how much mana you are regening per 5 seconds, the actual mana tick is every 3 seconds, so it will appear smaller.

Closing this due to lack of information.

**Closed** 2019-08-13 10:59 UTC
