### ISSUE TITLE
Water doesn't break fall damage AND you stay mounted on the ocean floor.

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#363] opened 2018-12-14 00:21 UTC
As title.
![image](https://user-images.githubusercontent.com/45749087/49975539-6856a780-ff0c-11e8-8c92-d1d80af78350.png)

**Comment by Ziggy-QA** [comment] 2018-12-14 02:57
I have just investigate this issue.

I found that as of now, Players are unable to swim in water. Instead, they can only walk on the surface. Players will also take fall damage when landing in water due to the player continuing to "fall" while in water. This has been confirmed and marked as high priority.

**Closed** 2018-12-17 04:52 UTC
Labels: Confirmed, Fixed, High Priority
