### ISSUE TITLE
Quest: Disrupt Their Reinforcements Bugged

### ISSUE THREAD

**Issue by rhunon** [elysium-project/tbc-bug-tracker#640] opened 2019-02-20 17:21 UTC
**Summary:** 
Portal Xilus says out of range from every point, even when the character is as close as it can be
Can’t even click on Portal Kruul, doest show anything when I hover my mouse over it.

**Steps to Reproduce:** 
Just try to click on it with the required items.

**Expected Results:** 
Able to open and complete quest

**Actual Result:**
Says out of range for Xilus and nothing shows up for Kruul

**Additional Information:**

**Comment by AfterShave** [comment] 2019-02-26 21:29
Been reported for months

**Comment by Ziggy-QA** [comment] 2019-03-07 11:44
Duplicate of #12

**Closed by Ziggy-QA** 2019-03-07 11:44 UTC
