### ISSUE TITLE
Temple Event in Zul'Farrak

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#476] opened 2018-12-22 06:52 UTC
The temple event in Zul'Farrak has a number of problems. Sergeant Bly and his companions will not present the option to start the event, they will not advance forward to the temple mount, the enemy trolls will not attack up the stairs, the second wave will not spawn after the first wave is killed and the second wave will not allow the friendly mob, Weegli Blastfuse, the option to blow open the door to the boss.

**Comment by Igraina** [comment] 2018-12-22 07:37
Duplicate of https://github.com/elysium-project/tbc-bug-tracker/issues/339

**Closed** 2018-12-23 08:49 UTC
