### ISSUE TITLE
quest "Corki's gone missing again!" Corki does not escape. Again... 

### ISSUE THREAD

**Issue by miecachu** [elysium-project/tbc-bug-tracker#550] opened 2019-01-07 15:19 UTC
Quest "Corki's gone missing again!"
This is the follow up quest for quest #492 where Corki did not want to escape from the cage.

This time he does not escape the cage either after opening it for him.

Nagrand loc. 39, 27 in the cave (so underground)

**Comment by Ziggy-QA** [comment] 2019-01-07 16:20
Hi, this is a duplicate of #492 and as a result this issue will be closed.

Thank you for your report regardless! If you have anything to add please comment in that issue!

**Closed by Ziggy-QA** 2019-01-07 16:20 UTC
