### ISSUE TITLE
I work... For the horde!

### ISSUE THREAD

**Issue by OyvindBentaas** [elysium-project/tbc-bug-tracker#335] opened 2018-12-11 15:43 UTC
When picking up the salvaged wood and metal, i can't pick up any more metal after reaching 8/8 wood.

**Comment by Drunkruptor** [comment] 2018-12-17 23:57
I was able to complete this quest with no issue on 2 different characters.

**Comment by OyvindBentaas** [comment] 2018-12-18 23:04
Okay, i had to relog twice before i was able to finish it. 
If you can't reproduce it, I'm sorry for the inconvenience :)

**Comment by ZicoQA** [comment] 2018-12-23 14:06
I tried reproducing in 2 different chars and the quest went well.

**Comment by Ziggy-QA** [comment] 2019-01-21 07:18
I'm gonna close this issue because I think this is client side.

**Closed by Ziggy-QA** 2019-01-21 07:18 UTC
Labels: Investigating, Quest / Outdoor Content
