### ISSUE TITLE
Quest: Redeeming the Dead broken

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#291] opened 2018-12-10 01:43 UTC
The mob doesn't resurrect when you use the filled vial on it.

**Comment by ApertureBear** [comment] 2018-12-14 07:02
I'd like to confirm this is not closed by the scripting fixes. Using the vial on Blood Knight Stillblade still has no effect, consumed the item, and does not progress the quest.

**Comment by Igraina** [comment] 2018-12-19 07:34
Quest: http://db.hellfire-tbc.com/?quest=9685
NPC: http://db.hellfire-tbc.com/?npc=17768
Item: http://db.hellfire-tbc.com/?item=24184

**Comment by Ziggy-QA** [comment] 2018-12-19 17:20
Duplicate of #222 and has been fixed

**Closed by Ziggy-QA** 2018-12-19 17:20 UTC
