### ISSUE TITLE
Zul Farrak

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#484] opened 2018-12-23 17:53 UTC
![1211122](https://user-images.githubusercontent.com/45742114/50386233-1aa02300-06f4-11e9-97c0-be6e4e9678f8.jpg)

in general your dungeon does not work)) and I am more than confident that 50% of the subtitles of Vanilla also need to be corrected) 

in this screenshot, after the opening of the dungeon .. NPS just attacks you, and then nothing happens, although first of all they have to go down to the bottom and start something in the form of the Quemes line 
https://www.youtube.com/watch?v=yXjrtPoPH2o

**Comment by Ziggy-QA** [comment] 2018-12-23 17:58
Hi @Davun4u 

This is a duplicate of #339 please post there any additional information.

Thank you!

**Closed by Ziggy-QA** 2018-12-23 17:58 UTC
