### ISSUE TITLE
quest bug))

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#453] opened 2018-12-19 16:45 UTC
[The Demoniac Scryer] not work 

https://www.youtube.com/watch?v=X0htxrrWUb8   work imho )

**Comment by Igraina** [comment] 2018-12-19 17:07
Duplicate of https://github.com/elysium-project/tbc-bug-tracker/issues/423

**Closed** 2018-12-20 19:20 UTC
