### ISSUE TITLE
Earth Shield not working as intended

### ISSUE THREAD

**Issue by Hellishcrew** [elysium-project/tbc-bug-tracker#1056] opened 2019-10-25 23:58 UTC
**Summary:** 
A resto shamans Earth Shield should trigger after the person with the shield takes damage and heal the person for a certain amount of HP. Atm the heal from earth shield is applied before the damage is taken, thus the heal is always overheal as long as the tank is topped at 100%
**Steps to Reproduce:** 
Earth Shields heal has to trigger AFTER the damage not before.
**Expected Results:** 
Earth Shield heals a target which took damage instead of producing overheal.
**Actual Result:**
Looking at our Raidlogs: 80% of the amount healed from Earth Shield goes into overheal since it always overheals when the tank is at 100% HP before.
**Additional Information:**

**Comment by IvanDanshin** [comment] 2019-12-11 02:50
Working as intended now. We can close this.
https://i.gyazo.com/178cb2b380c4a7abf9b404bc27cb3aa1.png

**Closed** 2019-12-13 01:44 UTC
Labels: Fixed, Investigating
