### ISSUE TITLE
Quest: Mazzranache [quest=766]

### ISSUE THREAD

**Issue by Medecc6** [elysium-project/tbc-bug-tracker#591] opened 2019-01-30 01:41 UTC
**Summary:**  The quest does not recognize Flatland Cougar Femur [item=4805] as an item in my inventory, despite having it, so the quest cannot be completed.

**Steps to Reproduce:** Kill Flatland Cougar [npc=3035] until they drop a Flatland Cougar Femur.

**Expected Results:** Quest changes to acknowledge the presence of the item in the inventory.

**Actual Result:** Quest does not recognize the item, despite it being labeled as a Quest Item.

**Additional Information:**

ADDENDUM: Upon deleting the femur and killing more cougars, I got another one and it triggered the quest, still a bug?

**Comment by McMittens** [comment] 2019-02-18 08:06
I was not able to reproduce this issue. 
There can be client-sided issues where a quest item doesn't get recognized. Those can usually be resolved with a relog or restart of the game and there's nothing we can do to prevent it from server side. :/

Closing this issue for now, if you find a way to reproduce this please comment!

**Closed by McMittens** 2019-02-18 08:06 UTC
