### ISSUE TITLE
Quest: "A Dip in the Moonwell"

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#359] opened 2018-12-13 15:54 UTC
[A Dip in the Moonwell] (quest)
need fix

**Comment by Ziggy-QA** [comment] 2018-12-14 02:04
@Davun4u , Can you please tell me the actual bug related to this quest?

"need fix" is not sufficent.

Please respond.

**Comment by Davun4u** [comment] 2018-12-15 08:41
https://www.youtube.com/watch?v=loAIeZbYC8s 

Here is information about this quest and its proper operation.

**Comment by Igraina** [comment] 2018-12-18 13:40
Quest: http://db.hellfire-tbc.com/?quest=9433
Item: http://db.hellfire-tbc.com/?item=23675
Interacting with console: http://db.hellfire-tbc.com/?spell=30009
The interaction summons the robot (http://db.hellfire-tbc.com/?npc=17178), which will be under the players direct control (http://db.hellfire-tbc.com/?spell=29989), then you can walk to the moonwell and use the robots ability (http://db.hellfire-tbc.com/?spell=29992) while standing it the water. This will place the quest item (http://db.hellfire-tbc.com/?item=23670) in the players inventory.

**Comment by Ziggy-QA** [comment] 2018-12-27 22:15
I am closing this issue. Its a duplicate of #303

**Closed by Ziggy-QA** 2018-12-27 22:15 UTC
Labels: Investigating, Vanilla
