### ISSUE TITLE
Mob spawn is too close

### ISSUE THREAD

**Issue by xergio** [elysium-project/tbc-bug-tracker#302] opened 2018-12-10 08:03 UTC
When we run with a fast mount, the mobs spawn right over you, even the grass have more visual range than the mobs, we should be able to see the mobs at >60y, not at 10. This probably is only a server setting, or a way to maintain the PTR in low load, but it's not right in production.

**Comment by Ziggy-QA** [comment] 2018-12-10 11:46
Are you talking about the distance that NPC's show up when you walk near their location? You say its too short?

Please respond

**Comment by xergio** [comment] 2018-12-10 11:58
Yes.

**Comment by xergio** [comment] 2018-12-10 19:35
One more example: https://streamable.com/0vmjn

Today seems like they spawn at 20y, yesterday was a bit closer

**Comment by Ziggy-QA** [comment] 2018-12-11 12:44
The visibility distance of NPCs currently coincide with what they are set as (which is 1 yard). Because this is working as intended, I am closing this issue.

**Closed by Ziggy-QA** 2018-12-11 12:44 UTC
Labels: Invalid / Duplicate
