### ISSUE TITLE
Quest Item: Unable to Open Arelion's Knapsack

### ISSUE THREAD

**Issue by rhunon** [elysium-project/tbc-bug-tracker#641] opened 2019-02-20 17:23 UTC
**Summary:** 
I can see the knapsack at the Pools of Aggonar, the wheel indicating that it can be opened appears but nothing happens when I click on it

**Steps to Reproduce:** 
Just get the quest and go there

**Expected Results:**
Able to open the knapsack and get quest item 

**Actual Result:**
Unable to pick up quest item

**Additional Information:**

**Comment by Ziggy-QA** [comment] 2019-03-07 11:43
Duplicate of #543

**Closed by Ziggy-QA** 2019-03-07 11:43 UTC
Labels: Invalid / Duplicate
